menu:
    Blog: /
    Archives: /archives/
    Email: sendto:prikevs@gmail.com
    github: https://github.com/prikevs
    rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Analytics
# google-analytics:
ga: UA-72789490-1
# baidu-analytics:
ba:

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
